DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    first VARCHAR (255) NOT NULL,
    last VARCHAR (255) NOT NULL,
    email VARCHAR (255) NOT NULL UNIQUE,
    password VARCHAR (255) NOT NULL,
    bio VARCHAR (255),
    avatar VARCHAR (350),
    created_at TIMESTAMP DEFAULT
    CURRENT_TIMESTAMP
);
